control_constants:
  update_rate: 50.0 # [Hz]   publish motor torques with this frequency.

  # controller_type:        # "2D","3D","drive", this value is set through launch file!
  # motors_controller_type: # "PositionJointInterface", "VelocityJointInterface", "EffortJointInterface" this value is set through launch file.

  #Control2D Gains:
  gains_2D_Kxz: [ -0.3162,  24.8947,  -0.5533, 7.1600] #[ -0.3162,  24.8947,  -0.5533, 7.1600]
  gains_2D_Kyz: [ -0.3162,  24.8947,  -0.5533, 7.1600]
  Kr: 5.32
  Tv: 1 #[sec]

  #Geometry constants:
  alpha: 0.78539816339 #[rad]   45째
  beta: -1.57079       #[rad]   90째  120째 = 2pi/3 = 2.09439510239 our beta: 60째 we have an offset -> P. 13

  #Control3D Gains:

