gripper_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - gripper_servo_joint
    
  constraints:
    goal_time: &goal_time_constraint  4.0
    stopped_velocity_tolerance: 1.0
    gripper_servo_joint:
      goal: &goal_pos_constraint 0.5
      trajectory: &trajectory_pos_constraint 1.0
