arm_joint_1_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_1
  pid: {p: 100.0, d: 0.0, i: 0.0, i_clamp: 1.0}

arm_joint_2_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_2
  pid: {p: 100.0, d: 0.0, i: 0.0, i_clamp: 1.0}

arm_joint_3_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_3
  pid: {p: 100.0, d: 0.0, i: 0.0, i_clamp: 1.0}

arm_joint_4_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_4
  pid: {p: 100.0, d: 0.0, i: 0.0, i_clamp: 1.0}
