# Position Controllers ---------------------------------------
# Velocity Controllers ---------------------------------------
# ballbot:
wheel1_position_controller:
   type: effort_controllers/JointEffortController
   joint: wheel1_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}

wheel2_position_controller:
   type: effort_controllers/JointEffortController
   joint: wheel2_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}

wheel3_position_controller:
   type: effort_controllers/JointEffortController
   joint: wheel3_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}

#Notes Markus:
#types: Position or Velocity Controller
#pid:  controlled via PID type/effort controller. or JointEffortController, JointPositionController,JointVelocityController
#p: 100.0, i: 0.01, d: 10.0
