wheel1_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel1_joint
  pid: {p: 0.1, i: 0.0, d: 0.00001}

wheel2_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel2_joint
  pid: {p: 0.1, i: 0.0, d: 0.00001}

wheel3_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel3_joint
  pid: {p: 0.1, i: 0.0, d: 0.00001}


#Notes Markus:
#types: Position or Velocity Controller
#pid:  controlled via PID type/effort controller.
